### ISSUE TITLE
Error rendering Tera template 

### ISSUE THREAD

**Issue by robhodl** [yzernik/squeakroad#604] opened 2022-09-06 23:23 UTC
Starting the app in MacOS, I get 500 server error:
```
GET / text/html:
   >> Matched: (index) GET /?<page_num>
   >> Error rendering Tera template 'listingsindex'.
   >> Failed to render 'listingsindex' (error happened in 'base').
   >> Variable `base_context.admin_settings.market_name` not found in context while rendering 'listingsindex'
   >> Template 'listingsindex' failed to render.
   >> Outcome: Failure
   >> No 500 catcher registered. Using Rocket default.
   >> Response succeeded.
```
```
$ cargo --version                                                                   
cargo 1.63.0 (fd9c4297c 2022-07-01)

$ sqlite3 --version                 
3.37.0 2021-12-09 01:34:53 9ff244ce0739f8ee52a3e9671adb4ee54c83c640b02e3f9d185fd2f9a179aapl
```
Using a DB browser, I see there are no rows in the `admin_settings` table.

Here's the full output of cargo run (with above error at the end):
```
$ cargo run                                                                                     <master ✗>
    Updating crates.io index
    Updating git repository `https://github.com/yzernik/Rocket`
    Updating git repository `https://github.com/yzernik/rocket_auth`
   Compiling version_check v0.9.4
   Compiling proc-macro2 v1.0.43
   Compiling quote v1.0.21
   Compiling unicode-ident v1.0.3
   Compiling libc v0.2.132
   Compiling syn v1.0.99
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.1.0
   Compiling once_cell v1.14.0
   Compiling serde_derive v1.0.144
   Compiling typenum v1.15.0
   Compiling memchr v2.5.0
   Compiling cc v1.0.73
   Compiling pin-project-lite v0.2.9
   Compiling bytes v1.2.1
   Compiling futures-core v0.3.24
   Compiling log v0.4.17
   Compiling scopeguard v1.1.0
   Compiling serde v1.0.144
   Compiling smallvec v1.9.0
   Compiling futures-task v0.3.24
   Compiling itoa v1.0.3
   Compiling futures-channel v0.3.24
   Compiling parking_lot_core v0.9.3
   Compiling fnv v1.0.7
   Compiling pin-utils v0.1.0
   Compiling pkg-config v0.3.25
   Compiling bitflags v1.3.2
   Compiling futures-sink v0.3.24
   Compiling subtle v2.4.1
   Compiling futures-util v0.3.24
   Compiling futures-io v0.3.24
   Compiling ppv-lite86 v0.2.16
   Compiling percent-encoding v2.1.0
   Compiling regex-syntax v0.6.27
   Compiling opaque-debug v0.3.0
   Compiling libm v0.2.5
   Compiling httparse v1.8.0
   Compiling tower-service v0.3.2
   Compiling try-lock v0.2.3
   Compiling unicode-xid v0.2.3
   Compiling base64 v0.13.0
   Compiling yansi v0.5.1
   Compiling httpdate v1.0.2
   Compiling untrusted v0.7.1
   Compiling vcpkg v0.2.15
   Compiling byteorder v1.4.3
   Compiling rustls v0.20.6
   Compiling anyhow v1.0.64
   Compiling parking_lot_core v0.8.5
   Compiling siphasher v0.3.10
   Compiling async-trait v0.1.57
   Compiling tinyvec_macros v0.1.0
   Compiling crossbeam-utils v0.8.11
   Compiling serde_json v1.0.85
   Compiling time-macros v0.2.4
   Compiling fastrand v1.8.0
   Compiling ryu v1.0.11
   Compiling remove_dir_all v0.5.3
   Compiling mime v0.3.16
   Compiling unicode-bidi v0.3.8
   Compiling minimal-lexical v0.2.1
   Compiling matches v0.1.9
   Compiling spin v0.5.2
   Compiling ref-cast v1.0.9
   Compiling unicode-segmentation v1.9.0
   Compiling inlinable_string v0.1.15
   Compiling getrandom v0.1.16
   Compiling core-foundation-sys v0.8.3
   Compiling block-padding v0.2.1
   Compiling crossbeam-queue v0.3.6
   Compiling rand_core v0.6.3
   Compiling state v0.5.3
   Compiling unicode_categories v0.1.1
   Compiling lazy_static v1.4.0
   Compiling hex v0.4.3
   Compiling encoding_rs v0.8.31
   Compiling maybe-uninit v2.0.0
   Compiling base64ct v1.5.2
   Compiling tower-layer v0.3.1
   Compiling crc-catalog v2.1.0
   Compiling const-oid v0.7.1
   Compiling prettyplease v0.1.19
   Compiling foreign-types-shared v0.1.1
   Compiling same-file v1.0.6
   Compiling glob v0.3.0
   Compiling fixedbitset v0.4.2
   Compiling ucd-trie v0.1.5
   Compiling paste v1.0.9
   Compiling ident_case v1.0.1
   Compiling strsim v0.9.3
   Compiling openssl v0.10.41
   Compiling event-listener v2.5.3
   Compiling multimap v0.8.3
   Compiling tokio-openssl v0.6.3
   Compiling unic-common v0.9.0
   Compiling unic-char-range v0.9.0
   Compiling binascii v0.1.4
   Compiling http-range-header v0.3.0
   Compiling sync_wrapper v0.1.1
   Compiling num-bigint-dig v0.8.1
   Compiling stable_deref_trait v1.2.0
   Compiling matchit v0.5.0
   Compiling version_check v0.1.5
   Compiling quick-error v1.2.3
   Compiling crc32fast v1.3.2
   Compiling adler v1.0.2
   Compiling deunicode v0.4.3
   Compiling termcolor v1.1.3
   Compiling fallible-streaming-iterator v0.1.9
   Compiling derive_builder v0.9.0
   Compiling signature v1.6.0
   Compiling constant_time_eq v0.1.5
   Compiling if_chain v1.0.2
   Compiling arrayref v0.3.6
   Compiling linked-hash-map v0.5.6
   Compiling fallible-iterator v0.2.0
   Compiling arrayvec v0.7.2
   Compiling hyper-openssl v0.9.2
   Compiling crc24 v0.1.6
   Compiling keccak v0.1.2
   Compiling safemem v0.3.3
   Compiling humansize v1.1.1
   Compiling bmp-monochrome v1.0.0
   Compiling normpath v0.3.2
   Compiling circular v0.3.0
   Compiling bitfield v0.13.2
   Compiling instant v0.1.12
   Compiling tracing-core v0.1.29
   Compiling thread_local v1.1.4
   Compiling generic-array v0.14.6
   Compiling ahash v0.7.6
   Compiling uncased v0.9.7
   Compiling proc-macro2-diagnostics v0.9.1
   Compiling cookie v0.16.0
   Compiling figment v0.10.7
   Compiling multer v2.0.3
   Compiling rocket v0.5.0-rc.2 (https://github.com/yzernik/Rocket?branch=upgrade_sqlx_v_0_6#5a2ea549)
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling rocket_sync_db_pools v0.1.0-rc.2 (https://github.com/yzernik/Rocket?branch=upgrade_sqlx_v_0_6#5a2ea549)
   Compiling lock_api v0.4.8
   Compiling slab v0.4.7
   Compiling tokio v1.21.0
   Compiling indexmap v1.9.1
   Compiling num-traits v0.2.15
   Compiling num-integer v0.1.45
   Compiling atomic v0.5.1
   Compiling num-iter v0.1.43
   Compiling num-rational v0.2.4
   Compiling cmake v0.1.48
   Compiling http v0.2.8
   Compiling rustls-pemfile v1.0.1
   Compiling gexiv2-sys v1.2.0
   Compiling ring v0.16.20
   Compiling openssl-sys v0.9.75
   Compiling clear_on_drop v0.2.5
   Compiling tinyvec v1.6.0
   Compiling form_urlencoded v1.0.1
   Compiling libsqlite3-sys v0.24.2
   Compiling heck v0.4.0
   Compiling rand v0.8.5
   Compiling crc v3.0.0
   Compiling foreign-types v0.3.2
   Compiling pem-rfc7468 v0.3.1
   Compiling walkdir v2.3.2
   Compiling unic-ucd-version v0.9.0
   Compiling unic-char-property v0.9.0
   Compiling owning_ref v0.3.3
   Compiling humantime v1.3.0
   Compiling miniz_oxide v0.5.4
   Compiling slug v0.1.4
   Compiling nom v4.2.3
   Compiling ed25519 v1.5.2
   Compiling linked_hash_set v0.1.4
   Compiling blake2b_simd v1.0.0
   Compiling qr_code v1.1.0
   Compiling tracing v0.1.36
   Compiling http-body v0.4.5
   Compiling unic-ucd-segment v0.9.0
   Compiling unicode-normalization v0.1.21
   Compiling num_cpus v1.13.1
   Compiling socket2 v0.4.7
   Compiling getrandom v0.2.7
   Compiling signal-hook-registry v1.4.0
   Compiling cpufeatures v0.2.5
   Compiling num_threads v0.1.6
   Compiling tempfile v3.3.0
   Compiling atty v0.2.14
   Compiling dirs-sys v0.3.7
   Compiling time v0.1.44
   Compiling rand v0.4.6
   Compiling fsevent-sys v2.0.1
   Compiling filetime v0.2.17
   Compiling aho-corasick v0.7.19
   Compiling stable-pattern v0.1.0
   Compiling nom v7.1.1
   Compiling bstr v0.2.17
   Compiling buf_redux v0.8.4
   Compiling mio v0.8.4
   Compiling want v0.3.0
   Compiling iana-time-zone v0.1.47
   Compiling rust-argon2 v1.0.0
   Compiling smallvec v0.6.14
   Compiling unic-segment v0.9.0
   Compiling flate2 v1.0.24
   Compiling idna v0.2.3
   Compiling stringprep v0.1.2
   Compiling phf_shared v0.11.1
   Compiling time v0.3.14
   Compiling dirs v4.0.0
   Compiling rand_core v0.5.1
   Compiling fsevent v0.4.0
   Compiling parking_lot v0.12.1
   Compiling spin v0.9.4
   Compiling parking_lot v0.11.2
   Compiling regex v1.6.0
   Compiling atoi v1.0.0
   Compiling block-buffer v0.10.3
   Compiling crypto-common v0.1.6
   Compiling cipher v0.3.0
   Compiling universal-hash v0.4.1
   Compiling digest v0.9.0
   Compiling aead v0.4.3
   Compiling block-buffer v0.9.0
   Compiling crypto-bigint v0.3.2
   Compiling parking_lot_core v0.2.14
   Compiling phf_generator v0.11.1
   Compiling phf v0.11.1
   Compiling rand_chacha v0.3.1
   Compiling hashbrown v0.12.3
   Compiling hashbrown v0.11.2
   Compiling url v2.2.2
   Compiling dotenvy v0.15.3
   Compiling rand_chacha v0.2.2
   Compiling notify v4.0.17
   Compiling scheduled-thread-pool v0.2.6
   Compiling futures-intrusive v0.4.0
   Compiling webpki v0.22.0
   Compiling sct v0.7.0
   Compiling globset v0.4.9
   Compiling env_logger v0.7.1
   Compiling parse-zoneinfo v0.3.0
   Compiling digest v0.10.3
   Compiling aes v0.7.5
   Compiling ctr v0.8.0
   Compiling cfb-mode v0.7.1
   Compiling cast5 v0.10.0
   Compiling blowfish v0.8.0
   Compiling block-modes v0.8.1
   Compiling twofish v0.6.0
   Compiling des v0.7.0
   Compiling polyval v0.5.3
   Compiling sha2 v0.9.9
   Compiling sha3 v0.9.1
   Compiling ripemd160 v0.9.1
   Compiling sha-1 v0.9.8
   Compiling md-5 v0.9.1
   Compiling futures v0.3.24
   Compiling futures-executor v0.3.24
   Compiling chrono v0.4.22
   Compiling parking_lot v0.4.8
   Compiling phf_codegen v0.11.1
   Compiling der v0.5.1
   Compiling hashlink v0.7.0
   Compiling hashlink v0.8.0
   Compiling rand v0.7.3
   Compiling synstructure v0.12.6
   Compiling darling_core v0.10.2
   Compiling validator_types v0.15.0
   Compiling r2d2 v0.8.10
   Compiling webpki-roots v0.22.4
   Compiling hyper v0.14.20
   Compiling tokio-stream v0.1.9
   Compiling pretty_env_logger v0.4.0
   Compiling ignore v0.4.18
   Compiling sha2 v0.10.5
   Compiling hmac v0.12.1
   Compiling ghash v0.4.4
   Compiling chrono-tz-build v0.0.3
   Compiling chashmap v2.2.2
   Compiling rexiv2 v0.9.1
   Compiling rusqlite v0.27.0
   Compiling spki v0.5.4
   Compiling petgraph v0.6.2
   Compiling devise_core v0.3.1
   Compiling tokio-macros v1.8.0
   Compiling futures-macro v0.3.24
   Compiling tracing-attributes v0.1.22
   Compiling pin-project-internal v1.0.12
   Compiling thiserror-impl v1.0.34
   Compiling pear_codegen v0.2.3
   Compiling async-stream-impl v0.3.3
   Compiling zeroize_derive v1.3.2
   Compiling ref-cast-impl v1.0.9
   Compiling uuid-macro-internal v1.1.2
   Compiling openssl-macros v0.1.0
   Compiling fehler-macros v1.0.0
   Compiling validator_derive v0.15.0
   Compiling num-derive v0.3.3
   Compiling hkdf v0.12.3
   Compiling aes-gcm v0.9.4
   Compiling globwalk v0.8.1
   Compiling r2d2_sqlite v0.20.0
   Compiling chrono-tz v0.6.3
   Compiling tokio-rustls v0.23.4
   Compiling darling_macro v0.10.2
   Compiling devise_codegen v0.3.1
   Compiling pin-project v1.0.12
   Compiling pear v0.2.3
   Compiling thiserror v1.0.34
   Compiling async-stream v0.3.3
   Compiling zeroize v1.5.7
   Compiling sqlx-rt v0.6.1
   Compiling darling v0.10.2
   Compiling devise v0.3.1
   Compiling flume v0.10.14
   Compiling tracing-futures v0.2.5
   Compiling pest v2.3.0
   Compiling curve25519-dalek v3.2.0
   Compiling pkcs8 v0.8.0
   Compiling derive_builder_core v0.9.0
   Compiling rocket_db_pools_codegen v0.1.0-rc.2 (https://github.com/yzernik/Rocket?branch=upgrade_sqlx_v_0_6#5a2ea549)
   Compiling rocket_sync_db_pools_codegen v0.1.0-rc.2 (https://github.com/yzernik/Rocket?branch=upgrade_sqlx_v_0_6#5a2ea549)
   Compiling fehler v1.0.0
   Compiling axum-core v0.2.7
   Compiling x25519-dalek v1.1.1
   Compiling pest_meta v2.3.0
   Compiling pkcs1 v0.3.3
   Compiling tokio-util v0.7.3
   Compiling tokio-io-timeout v1.2.0
   Compiling pest_generator v2.3.0
   Compiling either v1.8.0
   Compiling toml v0.5.9
   Compiling uuid v1.1.2
   Compiling ubyte v0.10.3
   Compiling ed25519-dalek v1.0.1
   Compiling h2 v0.3.14
   Compiling tower v0.4.13
   Compiling itertools v0.10.3
   Compiling pest_derive v2.3.0
   Compiling validator v0.15.0
   Compiling which v4.3.0
   Compiling rocket_http v0.5.0-rc.2 (https://github.com/yzernik/Rocket?branch=upgrade_sqlx_v_0_6#5a2ea549)
   Compiling rsa v0.6.1
   Compiling tower-http v0.3.4
   Compiling sqlformat v0.1.8
   Compiling prost-build v0.10.4
   Compiling pgp v0.8.0
   Compiling sqlx-core v0.6.1
   Compiling prost-derive v0.10.1
   Compiling rocket_codegen v0.5.0-rc.2 (https://github.com/yzernik/Rocket?branch=upgrade_sqlx_v_0_6#5a2ea549)
   Compiling tera v1.17.0
   Compiling prost v0.10.4
   Compiling prost-types v0.10.1
   Compiling hyper-timeout v0.4.1
   Compiling axum v0.5.15
   Compiling sqlx-macros v0.6.1
   Compiling tonic v0.7.2
   Compiling sqlx v0.6.1
   Compiling tonic-openssl v0.2.0
   Compiling rocket_dyn_templates v0.1.0-rc.2 (https://github.com/yzernik/Rocket?branch=upgrade_sqlx_v_0_6#5a2ea549)
   Compiling rocket_db_pools v0.1.0-rc.2 (https://github.com/yzernik/Rocket?branch=upgrade_sqlx_v_0_6#5a2ea549)
   Compiling rocket_auth v0.4.0 (https://github.com/yzernik/rocket_auth?branch=internal_branch_for_rocket_sqlx_0_6_0_post3#5f24519b)
   Compiling tonic-build v0.7.2
   Compiling tonic_openssl_lnd v0.1.5
   Compiling squeakroad v0.1.14 (/Users/r/Documents/squeakroad)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 43s
     Running `target/debug/squeakroad`
Starting with config: Config { db_url: "db.sqlite", admin_username: "admin", admin_password: "pass", lnd_host: "localhost", lnd_port: 10001, lnd_tls_cert_path: "/Users/r/.polar/networks/1/volumes/lnd/alice/tls.cert", lnd_macaroon_path: "/Users/r/.polar/networks/1/volumes/lnd/alice/data/chain/bitcoin/regtest/admin.macaroon" }
LOGGER: STAGING SQLX
🔧 Configured for debug.
address: 127.0.0.1
port: 8000
workers: 8
max blocking threads: 512
ident: Rocket
limits: bytes = 8KiB, data-form = 10MiB, file = 10MiB, form = 32KiB, json = 1MiB, msgpack = 1MiB, string = 8KiB
temp dir: /var/folders/pj/dx0bx4wx16b65dhnsw7cwtrm0000gn/T/
http/2: true
keep-alive: 5s
tls: disabled
secret key: [generated]
Warning: secrets enabled without a stable `secret_key`
disable `secrets` feature or configure a `secret_key`
this becomes an error in non-debug profiles
shutdown: ctrlc = true, force = true, signals = [SIGTERM], grace = 2s, mercy = 3s
log level: normal
cli colors: true
📬 Routes:
(index) GET /?<page_num>
(get_login) GET /login
(post_login) POST /login
(post_signup) POST /signup
(get_signup) GET /signup
(logout) GET /logout
(FileServer: static) GET /<path..> [10]
(index) GET /user/<username>?<page_num>
(enable) PUT /user/<username>/enable
(disable) PUT /user/<username>/disable
(index) GET /about/
(index) GET /admin/
(index) GET /order/<id>
(ship) PUT /order/<id>/ship
(new_review) POST /order/<id>/new_review
(buyer_cancel) PUT /order/<id>/buyer_cancel
(seller_cancel) PUT /order/<id>/seller_cancel
(index) GET /search/?<search_text>&<page_num>
(index) GET /account/
(index) GET /listing/<id>
(submit) PUT /listing/<id>/submit
(reject) PUT /listing/<id>/reject
(approve) PUT /listing/<id>/approve
(deactivate) PUT /listing/<id>/deactivate
(admin_deactivate) PUT /listing/<id>/deactivate_as_admin
(index) GET /withdraw/
(new) POST /withdraw/new
(index) GET /withdrawal/<id>
(index) GET /new_listing/
(new) POST /new_listing/
(index) GET /top_sellers/?<page_num>
(index) GET /active_users/?<page_num>
(index) GET /user_profile/<username>
(index) GET /prepare_order/<id>?<shipping_option_id>&<quantity>
(new) POST /prepare_order/<id>/new
(index) GET /disabled_users/?<page_num>
(index) GET /my_paid_orders/?<page_num>
(index) GET /delete_listing/<id>
(delete) DELETE /delete_listing/<id>
(index) GET /seller_history/<username>?<page_num>
(index) GET /update_fee_rate/
(index) GET /update_pgp_info/
(update) POST /update_fee_rate/change
(update) POST /update_pgp_info/change
(index) GET /activate_account/
(index) GET /my_unpaid_orders/?<page_num>
(index) GET /deactivate_account/
(index) GET /market_liabilities/?<page_num>
(index) GET /update_market_name/
(index) GET /my_active_listings/?<page_num>
(index) GET /my_account_balance/?<page_num>
(new) POST /deactivate_account/new
(index) GET /account_activation/<id>
(update) POST /update_market_name/change
(index) GET /my_pending_listings/?<page_num>
(index) GET /deactivated_listings/?<page_num>
(index) GET /update_user_pgp_info/
(index) GET /my_rejected_listings/?<page_num>
(index) GET /my_processing_orders/?<page_num>
(update) POST /update_user_pgp_info/change
(index) GET /update_listing_images/<id>
(new) POST /update_listing_images/<id>/add_image
(delete) DELETE /update_listing_images/<id>/add_image/<image_id>
(set_primary) PUT /update_listing_images/<id>/set_primary/<image_id>
(index) GET /update_user_bond_price/
(index) GET /update_squeaknode_info/
(update) POST /update_user_bond_price/change
(update) POST /update_squeaknode_info/change
(index) GET /review_pending_listings/?<page_num>
(index) GET /my_unsubmitted_listings/?<page_num>
(index) GET /my_deactivated_listings/?<page_num>
(index) GET /update_shipping_options/<id>
(new) POST /update_shipping_options/<id>/add_shipping_option
(delete) DELETE /update_shipping_options/<id>/add_shipping_option/<shipping_option_id>
(index) GET /update_max_allowed_users/
(update) POST /update_max_allowed_users/change
(index) GET /update_user_squeaknode_info/
(update) POST /update_user_squeaknode_info/change
🥅 Catchers:
(not_authorized) 401
📡 Fairings:
SQLx Stage (ignite)
SQLx Migrations (ignite)
Prepare Order Stage (ignite)
Templating (ignite, liftoff, request)
Account Stage (ignite)
My Pending Listings Stage (ignite)
New Listing Stage (ignite)
Account Activation Stage (ignite)
My Rejected Listings Stage (ignite)
Remove expired user accounts (liftoff)
Active Users Stage (ignite)
Order Stage (ignite)
My Active Listings Stage (ignite)
Market Liabilies Stage (ignite)
User Stage (ignite)
Update Squeaknode Stage (ignite)
My Paid Orders Stage (ignite)
Listing Stage (ignite)
Seller History Stage (ignite)
User Profile Stage (ignite)
Pending Listings Stage (ignite)
Shield (liftoff, response, singleton)
Process Payments (liftoff)
Deactivated Listings Stage (ignite)
Top Sellers Stage (ignite)
Remove expired orders (liftoff)
Update User PGP Stage (ignite)
SQLx Create Admin User (ignite)
Update User Bond Price Stage (ignite)
My Account Balance Stage (ignite)
Update Fee Rate Stage (ignite)
Update Max Allowed Users Stage (ignite)
My Deactivated Listings Stage (ignite)
SQLx Create Users table (ignite)
'squeakroad' Database Pool (ignite, shutdown)
About Stage (ignite)
Listings Stage (ignite)
Update Market Name Stage (ignite)
My Unsubmitted Listings Stage (ignite)
My Processing Orders Stage (ignite)
Add Listing Images Stage (ignite)
My Unpaid Orders Stage (ignite)
Withdrawal Stage (ignite)
Delete Listing Stage (ignite)
Withdraw Stage (ignite)
Activate_Account Stage (ignite)
Add Shipping Options Stage (ignite)
Deactivate Account Stage (ignite)
Disabled Users Stage (ignite)
Update PGP Stage (ignite)
Update User Squeaknode Stage (ignite)
Manage config (ignite)
Auth Stage (ignite)
Search Stage (ignite)
Admin Stage (ignite)
🛡️ Shield:
   >> X-Frame-Options: SAMEORIGIN
   >> Permissions-Policy: interest-cohort=()
   >> X-Content-Type-Options: nosniff
📐 Templating:
   >> directory: templates
   >> engines: ["tera"]
🚀 Rocket has launched from http://127.0.0.1:8000
Starting subscribe invoices with latest settle index: 0
GET / text/html:
   >> Matched: (index) GET /?<page_num>
   >> Error rendering Tera template 'listingsindex'.
   >> Failed to render 'listingsindex' (error happened in 'base').
   >> Variable `base_context.admin_settings.market_name` not found in context while rendering 'listingsindex'
   >> Template 'listingsindex' failed to render.
   >> Outcome: Failure
   >> No 500 catcher registered. Using Rocket default.
   >> Response succeeded.
```

**Comment by yzernik** [comment] 2022-09-06 23:30
Thanks @robhodl 

I just noticed this error today (I think something changed in one of the upstream dependencies).

I just pushed a fix for this issue a few minutes ago:
https://github.com/yzernik/squeakroad/pull/602

**Comment by yzernik** [comment] 2022-09-06 23:34
Duplicate of https://github.com/yzernik/squeakroad/issues/603

**Closed** 2022-09-06 23:39 UTC
